In [13]:
import yfinance as yfin
import pandas as pd

In [14]:
dat = yfin.Ticker("NOBL")

In [15]:
# get historical market data
monthly = dat.history(period='1mo')

In [16]:
print(monthly)

                                 Open        High         Low       Close  \
Date                                                                        
2024-11-04 00:00:00-05:00  103.769997  104.510002  103.510002  103.790001   
2024-11-05 00:00:00-05:00  103.830002  104.870003  103.500000  104.870003   
2024-11-06 00:00:00-05:00  106.690002  107.349998  105.459999  106.059998   
2024-11-07 00:00:00-05:00  106.050003  106.330002  105.870003  105.900002   
2024-11-08 00:00:00-05:00  105.989998  106.760002  105.830002  106.489998   
2024-11-11 00:00:00-05:00  106.660004  107.419998  106.610001  106.849998   
2024-11-12 00:00:00-05:00  106.720001  106.860001  105.949997  106.029999   
2024-11-13 00:00:00-05:00  106.110001  106.570000  105.940002  106.379997   
2024-11-14 00:00:00-05:00  106.330002  106.430000  105.500000  105.540001   
2024-11-15 00:00:00-05:00  105.300003  105.730003  105.019997  105.129997   
2024-11-18 00:00:00-05:00  105.099998  105.680000  104.940002  105.529999   

In [28]:
volume = monthly['Volume']
volume

Date
2024-11-04 00:00:00-05:00    402400
2024-11-05 00:00:00-05:00    314400
2024-11-06 00:00:00-05:00    638100
2024-11-07 00:00:00-05:00    877200
2024-11-08 00:00:00-05:00    458300
2024-11-11 00:00:00-05:00    362700
2024-11-12 00:00:00-05:00    502700
2024-11-13 00:00:00-05:00    420000
2024-11-14 00:00:00-05:00    550700
2024-11-15 00:00:00-05:00    575300
2024-11-18 00:00:00-05:00    388400
2024-11-19 00:00:00-05:00    534500
2024-11-20 00:00:00-05:00    604400
2024-11-21 00:00:00-05:00    496100
2024-11-22 00:00:00-05:00    505100
2024-11-25 00:00:00-05:00    867400
2024-11-26 00:00:00-05:00    480900
2024-11-27 00:00:00-05:00    833400
2024-11-29 00:00:00-05:00    725300
2024-12-02 00:00:00-05:00    651600
2024-12-03 00:00:00-05:00    549600
Name: Volume, dtype: int64

In [20]:
dataset = pd.DataFrame(monthly)

In [23]:
high = dataset['High']
low = dataset['Low']
close = dataset['Close']

new_set = pd.concat([high, low, close], axis=1)
print(new_set)


                                 High         Low       Close
Date                                                         
2024-11-04 00:00:00-05:00  104.510002  103.510002  103.790001
2024-11-05 00:00:00-05:00  104.870003  103.500000  104.870003
2024-11-06 00:00:00-05:00  107.349998  105.459999  106.059998
2024-11-07 00:00:00-05:00  106.330002  105.870003  105.900002
2024-11-08 00:00:00-05:00  106.760002  105.830002  106.489998
2024-11-11 00:00:00-05:00  107.419998  106.610001  106.849998
2024-11-12 00:00:00-05:00  106.860001  105.949997  106.029999
2024-11-13 00:00:00-05:00  106.570000  105.940002  106.379997
2024-11-14 00:00:00-05:00  106.430000  105.500000  105.540001
2024-11-15 00:00:00-05:00  105.730003  105.019997  105.129997
2024-11-18 00:00:00-05:00  105.680000  104.940002  105.529999
2024-11-19 00:00:00-05:00  105.230003  104.269997  104.910004
2024-11-20 00:00:00-05:00  105.139999  104.309998  105.080002
2024-11-21 00:00:00-05:00  106.370003  104.879997  106.339996
2024-11-

In [27]:
import numpy as np
np_set = new_set.to_numpy()
print(np_set)

[[104.51000214 103.51000214 103.79000092]
 [104.87000275 103.5        104.87000275]
 [107.34999847 105.45999908 106.05999756]
 [106.33000183 105.87000275 105.90000153]
 [106.76000214 105.83000183 106.48999786]
 [107.41999817 106.61000061 106.84999847]
 [106.86000061 105.94999695 106.02999878]
 [106.56999969 105.94000244 106.37999725]
 [106.43000031 105.5        105.54000092]
 [105.73000336 105.01999664 105.12999725]
 [105.68000031 104.94000244 105.52999878]
 [105.23000336 104.26999664 104.91000366]
 [105.13999939 104.30999756 105.08000183]
 [106.37000275 104.87999725 106.33999634]
 [107.08999634 106.34999847 106.95999908]
 [108.26999664 107.45999908 107.91000366]
 [108.12000275 107.45999908 108.02999878]
 [108.79000092 108.09999847 108.12999725]
 [108.66000366 108.11000061 108.47000122]
 [108.48999786 107.47000122 108.06999969]
 [108.20999908 107.25       107.37999725]]
