# Notes

This notebook will review descriptive statistics for the dataset provided by Yahoo on Kaggle. Goals of of the project are in the main notes markdown file. This notebook will run descriptive statistics and define arrays based on those statistics. 

## Description
Here we are going to do a number of things.

1. We will import a spreadsheet
2. We will do some statistics in pandas
3. We will then use the spreadsheet to define an array in numpy
4. We will manipulate the array in numpy
5. We will also organize our stats by company once we have general descriptives

## List of descriptive statistics
- Counts
- Means
- Medians
- Maximums
- Minimums
- Range
- Variance
- Standard deviation

In [1]:
# import libraries and data

## Libraries
import numpy as np
import pandas as pd

## Data
yfin_csv = pd.read_csv(r'https://raw.githubusercontent.com/alexcrockett/Jupyter-Playground/personal/yfin_dataset/02-data/stock_details_5_years.csv')

### Becuase there is a lot of data we will just print the first 5 rows
print(yfin_csv.head(5))

                        Date        Open        High         Low       Close  \
0  2018-11-29 00:00:00-05:00   43.829761   43.863354   42.639594   43.083508   
1  2018-11-29 00:00:00-05:00  104.769074  105.519257  103.534595  104.636131   
2  2018-11-29 00:00:00-05:00   54.176498   55.007500   54.099998   54.729000   
3  2018-11-29 00:00:00-05:00   83.749496   84.499496   82.616501   83.678497   
4  2018-11-29 00:00:00-05:00   39.692784   40.064904   38.735195   39.037853   

      Volume  Dividends  Stock Splits Company  
0  167080000       0.00           0.0    AAPL  
1   28123200       0.00           0.0    MSFT  
2   31004000       0.00           0.0   GOOGL  
3  132264000       0.00           0.0    AMZN  
4   54917200       0.04           0.0    NVDA  


In [2]:
# Computing the descriptive statistics

## Count ------------------------------------------------------------------------------------------------
count_open = yfin_csv['Open'].count() # Count Open

## Mean ------------------------------------------------------------------------------------------------

### Per Columns
mean_open = yfin_csv['Open'].mean() # Mean Open
mean_high = yfin_csv['High'].mean() # Mean High
mean_low = yfin_csv['Low'].mean() # Mean Low
mean_close = yfin_csv['Close'].mean() # Mean Close
mean_volume = yfin_csv['Volume'].mean() # Mean Volume
mean_div = yfin_csv['Dividends'].mean() # Mean Dividends

### Dict.
di_mean1 = {
    "mean open": yfin_csv['Open'].mean(),
    "mean high": yfin_csv['High'].mean(),
    "mean low": yfin_csv['Low'].mean(),
    "mean close": yfin_csv['Close'].mean(),
    "mean volume": yfin_csv['Volume'].mean(),
    "mean dividends": yfin_csv['Dividends'].mean(),
}

## Median ------------------------------------------------------------------------------------------------

### Per Columns
median_open = yfin_csv['Open'].median() # median Open
median_high = yfin_csv['High'].median() # median High
median_low = yfin_csv['Low'].median() # median Low
median_close = yfin_csv['Close'].median() # median Close
median_volume = yfin_csv['Volume'].median() # median Volume
median_div = yfin_csv['Dividends'].median() # median Dividends

### Dict.
di_median1 = {
    "median open": yfin_csv['Open'].median(),
    "median high": yfin_csv['High'].median(),
    "median low": yfin_csv['Low'].median(),
    "median close": yfin_csv['Close'].median(),
    "median volume": yfin_csv['Volume'].median(),
    "median dividends": yfin_csv['Dividends'].median(),
}

## Min, Max, Range ------------------------------------------------------------------------------------------------

### Per Columns

#### max
max_open = yfin_csv['Open'].max() # max Open
max_high = yfin_csv['High'].max() # max High
max_low = yfin_csv['Low'].max() # max Low
max_close = yfin_csv['Close'].max() # max Close
max_volume = yfin_csv['Volume'].max() # max Volume
max_div = yfin_csv['Dividends'].max() # max Dividends

#### min
min_open = yfin_csv['Open'].min() # min Open
min_high = yfin_csv['High'].min() # min High
min_low = yfin_csv['Low'].min() # min Low
min_close = yfin_csv['Close'].min() # min Close
min_volume = yfin_csv['Volume'].min() # min Volume
min_div = yfin_csv['Dividends'].min() # min Dividends

#### range
range_open = abs(max_open - min_open) # range Open
range_high = abs(max_high - min_high) # range High
range_low = abs(max_low - min_low) # range Low
range_close = abs(max_close - min_close) # range Close
range_volume = abs(max_volume - min_volume) # range Volume
range_div = abs(max_div - min_div) # range Dividends

### Dict.

di_max_min_range = {
    "min open": yfin_csv['Open'].min(),
    "max open": yfin_csv['Open'].max(),
    "range open": range_open,
    "min high": yfin_csv['High'].min(),
    "max high": yfin_csv['High'].max(),
    "range high": range_high,
    "min low": yfin_csv['Low'].min(),
    "max low": yfin_csv['Low'].max(),
    "range low": range_low,
    "min close": yfin_csv['Close'].min(),
    "max close": yfin_csv['Close'].max(),
    "range close": range_close,
    "min volume": yfin_csv['Volume'].min(),
    "max volume": yfin_csv['Volume'].max(),
    "range volume": range_volume,
    "min dividends": yfin_csv['Dividends'].min(),
    "max dividends": yfin_csv['Dividends'].max(),
    "range dividends": range_div,
}

## Variance ------------------------------------------------------------------------------------------------

### Per Columns
var_open = yfin_csv['Open'].var() # var Open
var_high = yfin_csv['High'].var() # var High
var_low = yfin_csv['Low'].var() # var Low
var_close = yfin_csv['Close'].var() # var Close
var_volume = yfin_csv['Volume'].var() # var Volume
var_div = yfin_csv['Dividends'].var() # var Dividends

### Dict.
di_var1 = {
    "var open": yfin_csv['Open'].var(),
    "var high": yfin_csv['High'].var(),
    "var low": yfin_csv['Low'].var(),
    "var close": yfin_csv['Close'].var(),
    "var volume": yfin_csv['Volume'].var(),
    "var dividends": yfin_csv['Dividends'].var(),
}

## Standard Deviation ------------------------------------------------------------------------------------------------
### Per column
std_open = yfin_csv['Open'].std() # std Open
std_high = yfin_csv['High'].std() # std High
std_low = yfin_csv['Low'].std() # std Low
std_close = yfin_csv['Close'].std() # std Close
std_volume = yfin_csv['Volume'].std() # std Volume
std_div = yfin_csv['Dividends'].std() # std Dividends

### Dict.
di_std1 = {
    "std open": yfin_csv['Open'].std(),
    "std high": yfin_csv['High'].std(),
    "std low": yfin_csv['Low'].std(),
    "std close": yfin_csv['Close'].std(),
    "std volume": yfin_csv['Volume'].std(),
    "std dividends": yfin_csv['Dividends'].std(),
}

# Divider ------------------------------------------------------------------------------------------------

In [3]:
# Printing

## Count
print("Count: ", count_open)

### Print a seperator 
print("--------------------")

## Mean
for key, value in di_mean1.items():
    print(f"{key}: {value:.2f}")

print("--------------------")

## Median
for key, value in di_median1.items():
    print(f"{key}: {value:.2f}")

print("--------------------")

## Range data
for key, value in di_max_min_range.items():
    print(f"{key}: {value:.2f}")

print("--------------------")

## Variance
for key, value in di_var1.items():
    print(f"{key}: {value:.2f}")

print("--------------------")

## Standard Deviation
for key, value in di_std1.items():
    print(f"{key}: {value:.2f}")

print("--------------------")

# Divider ------------------------------------------------------------------------------------------------

Count:  602962
--------------------
mean open: 140.07
mean high: 141.85
mean low: 138.28
mean close: 140.10
mean volume: 5895601.18
mean dividends: 0.01
--------------------
median open: 79.18
median high: 80.13
median low: 78.19
median close: 79.18
median volume: 2228700.00
median dividends: 0.00
--------------------
min open: 1.05
max open: 6490.26
range open: 6489.21
min high: 1.06
max high: 6525.00
range high: 6523.94
min low: 1.03
max low: 6405.00
range low: 6403.97
min close: 1.03
max close: 6509.35
range close: 6508.32
min volume: 0.00
max volume: 1123003300.00
range volume: 1123003300.00
min dividends: 0.00
max dividends: 35.00
range dividends: 35.00
--------------------
var open: 75846.11
var high: 77842.78
var low: 73927.04
var close: 75888.11
var volume: 190880801357579.97
var dividends: 0.01
--------------------
std open: 275.40
std high: 279.00
std low: 271.90
std close: 275.48
std volume: 13815961.83
std dividends: 0.12
--------------------


In [4]:
# Creating vectors for the standard descriptive statistics

## Mean
mean_array = x_1 = np.array([float(format(mean_open, ".2f")), float(format(mean_high, ".2f")), float(format(mean_low, ".2f")), float(format(mean_close, ".2f"))]) #define array
x_1 = mean_array.reshape((-1, 1)) # Transpose array

print('Mean array')
print(x_1)

print("--------------------")

## Median
median_array = x_2 = np.array([float(format(median_open, ".2f")), float(format(median_high, ".2f")), float(format(median_low, ".2f")), float(format(median_close, ".2f"))]) #define array
x_2 = median_array.reshape((-1, 1)) # Transpose array

print('Median array')
print(x_2)

print("--------------------")

## Min
min_array = x_3 = np.array([float(format(min_open, ".2f")), float(format(min_high, ".2f")), float(format(min_low, ".2f")), float(format(min_close, ".2f"))]) #define array
x_3 = min_array.reshape((-1, 1)) # Transpose array

print('Min array')
print(x_3)

print("--------------------")

## Max
max_array = x_4 = np.array([float(format(max_open, ".2f")), float(format(max_high, ".2f")), float(format(max_low, ".2f")), float(format(max_close, ".2f"))]) #define array
x_4 = max_array.reshape((-1, 1)) # Transpose array

print('Max array')
print(x_4)

print("--------------------")

## Range
range_array = x_5 = np.array([float(format(range_open, ".2f")), float(format(range_high, ".2f")), float(format(range_low, ".2f")), float(format(range_close, ".2f"))]) #define array
x_5 = max_array.reshape((-1, 1)) # Transpose array

print('Range array')
print(x_5)

print("--------------------")

## Variance
var_array = x_6 = np.array([float(format(var_open, ".2f")), float(format(var_high, ".2f")), float(format(var_low, ".2f")), float(format(var_close, ".2f"))]) #define array
x_6 = var_array.reshape((-1, 1)) # Transpose array

print('Variance array')
print(x_6)

print("--------------------")

## Standard deviation
std_array = x_7 = np.array([float(format(std_open, ".2f")), float(format(std_high, ".2f")), float(format(std_low, ".2f")), float(format(std_close, ".2f"))]) #define array
x_7 = std_array.reshape((-1, 1)) # Transpose array

print('Standard Dev. array')
print(x_7)

print("--------------------")

Mean array
[[140.07]
 [141.85]
 [138.28]
 [140.1 ]]
--------------------
Median array
[[79.18]
 [80.13]
 [78.19]
 [79.18]]
--------------------
Min array
[[1.05]
 [1.06]
 [1.03]
 [1.03]]
--------------------
Max array
[[6490.26]
 [6525.  ]
 [6405.  ]
 [6509.35]]
--------------------
Range array
[[6490.26]
 [6525.  ]
 [6405.  ]
 [6509.35]]
--------------------
Variance array
[[75846.11]
 [77842.78]
 [73927.04]
 [75888.11]]
--------------------
Standard Dev. array
[[275.4 ]
 [279.  ]
 [271.9 ]
 [275.48]]
--------------------
